### ISSUE TITLE
Pre-emptively connecting clients to https

### ISSUE THREAD

**Issue by tedtms** [Jay-Rad/Remotely#17] opened 2019-04-20 02:55 UTC
Hey! Found your project on r/msp and absolutely love it so far, great work on this!

I have my install positioned behind a reverse proxy handling https:// which is working fine. However I've noticed that the client installation scripts point to the server using http://.

On my machines, this causes them to not want to connect, since I have nginx on my reverse proxy redirecting all http requests to https. On machines with the service already installed, adjusting the Host parameter in ConnectionInfo.json to use https:// and restarting the service immediately causes it to connect to the server. Alternatively, editing the client installer script before running it so that "hostname" reflects https:// accomplishes the same thing.

I tried enabling "RedirecttoHttps" in appsettings.json but I believe that setting assumes incoming connections are http and not already looking for https.

Is there a way to enforce https connections by the client through a server config option I may be missing, so that the script already points to it with https without needing to edit it? Thanks in advance!

**Comment by Jay-Rad** [comment] 2019-04-20 15:22
Hi!  Thanks for the kind words!  :)  I've gotten a lot of positive responses to that post, and it's been really awesome.  It's also helped uncover a few bugs, which has been really helpful.

For the client install scripts, the hostname is dynamically generated when you download it.  The hostname should reflect the URL that's coming from the browser.  So if you're at "https://myserver.com", the script should have HTTPS in it.  Same for HTTP.

Can you verify that you're browsing to https, and it's still downloading the script with http?

If so, can you try downloading the latest server files, overwriting the existing ones, and restarting the service?  https://remotely.lucency.co/Downloads/linux-x64/Remotely_Server.zip 

This was an issue previously that was supposed to be fixed.  Also, I need to get a better release process going to track fixes and such.  :)

**Comment by tedtms** [comment] 2019-04-21 02:03
Yep! Just confirmed now, both before and after the overwrite/update. I'm browsing to the server using HTTPS but the script downloads with the hostname listed as HTTP. Overwriting with the latest server files and restarting the service did not change this.

Now, I'm browsing to the server through a reverse proxy that's handling the https. I actually removed nginx and certbot from the server running Remotely, since I have those services being handled on the reverse proxy. So, technically, HTTPS is transparent to the Remotely server.... Maybe that's why Remotely thinks it's operating in HTTP? Because the traffic it's getting from the _proxy_ is HTTP?

**Comment by Jay-Rad** [comment] 2019-04-21 16:09
With the default configuration, Nginx does forward requests to .NET Core over HTTP (since encryption isn't needed to localhost).  However, info regarding the original request to Nginx is forwarded over through special headers, which .NET Core reads and merges into the request.

This is what I had fixed earlier.  All my tests since have shown that it's working properly.

I just deployed a fresh server at  https://test.lucency.co/, and it's also working.

Since I can't replicate it, I'd need access to a server that's exhibiting the issues.  Is there one I can access?  You can email me details if so.

**Comment by tedtms** [comment] 2019-04-21 17:15
What kind of access would you need? Would a copy of my nginx config be sufficient? Also, what email do you prefer?

**Comment by Jay-Rad** [comment] 2019-04-21 17:54
The more, the better. Ssh with sudo would be preferred. And if the web server is externally visible, that would be good.

If it's a prod server that you can't give access to, you'll need to replicate it on a server that I can access.

Everything works as intended with a fresh server. So it's likely a configuration issue.

I don't have a lot of spare time. So having direct access is the fastest way to troubleshoot.

My email is translucency@outlook.com

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by tedtms** [comment] 2019-04-21 18:11
Ok! I'll get the info for you tonight or tomorrow. Thanks again for all the time you've put into this and for your support!

**Comment by singularo** [comment] 2019-04-23 22:13
Similar situation here as OP, posting my nginx site config in case it helps diagnose:
`
root@ssl-nginx:/etc/nginx# cat sites-enabled/remotely 
server {
    listen 80;
    server_name remotely.myhostname.com;
    return 301 https://$host$request_uri;
}

server {

    listen 443 ssl http2;
    server_name remotely.myhostname.com;

    ssl_certificate           /etc/nginx/my_existing.crt;
    ssl_certificate_key       /etc/nginx/my_existing.key;

    ssl on;
    ssl_session_cache  builtin:1000  shared:SSL:10m;
    ssl_protocols  TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers HIGH:!aNULL:!eNULL:!EXPORT:!CAMELLIA:!DES:!MD5:!PSK:!RC4;
    ssl_prefer_server_ciphers on;

    access_log            /var/log/nginx/remotely.access.log;

    location / {

      proxy_set_header        Host $host;
      proxy_set_header        X-Real-IP $remote_addr;
      proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header        X-Forwarded-Proto $scheme;

      # Fix the “It appears that your reverse proxy set up is broken" error.
      proxy_pass          http://192.168.1.15:80;
      proxy_read_timeout  90;

      proxy_redirect      http://192.168.1.15:80 https://remotely.myhostname.com;
    }
}
`

**Comment by tedtms** [comment] 2019-04-23 23:35
Hey singularo, issue ended up being that my nginx reverse proxy was on another machine. The latest commit includes a fix for this and an extra config parameter where the proxy IPs have to be specified. I haven't gotten the chance to test it yet but the relevant info is in the new Readme. Cheers!

**Comment by Jay-Rad** [comment] 2019-04-23 23:46
As @tedtms mentioned, this is hopefully addressed in the latest version.

Unfortunately, my hosting provider is experiencing a major outage today, so the server install scripts aren't working.  I need to change my CI/CD to use GitHub releases instead of my server, I think.

Anyway, all configuration assumed that the Nginx server is on the same machine as the .NET Core app.  To get .NET Core to accept forwarded headers from another machine, that machine's IP must be added to a KnownProxies property.  It's explained here:  https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-2.2

I added a property in appsettings.json for this.  Here's the info I originally sent to @tedtms .

> Download and overwrite with the latest version again.
> 
> There's a new item in appsettings.json called KnownProxies.  It's a string array.  You'll need to add the Nginx machine's IP address to it.  This will allow .NET Core to receive forwarded headers from external machines.
> 
> Also, I added a note about this to my readme.  You can copy your appsettings.json settings to appsettings.Production.json.  .NET Core will automatically use this settings instead of appsettings.json when running in Production environment.  That way, you don't have to keep backing up/restoring your settings when upgrading.  You just need to remember to add new properties (if any are added to the project).

Once my hosting provider fixes the servers, you should be able to install and test the updates.

**Comment by Jay-Rad** [comment] 2019-04-24 15:30
My hosting provider is still down.  I think I'll be switching.  In the meantime, I got a release out on GitHub Releases.  The scripts still don't work yet since they're trying to download from my server, but at least the binaries are there to download.

https://github.com/Jay-Rad/Remotely/releases

**Comment by tedtms** [comment] 2019-04-28 01:24
@Jay-Rad Updated to the build you posted to GitHub but the scripts are still downloading with HTTP instead of HTTPS. I'm assuming I'm using the right syntax for the KnownProxies configuration?

![image](https://user-images.githubusercontent.com/49801453/56856893-bc4db000-6932-11e9-840f-cf7505870d4a.png)

Is there any adjustment that should be made to the nginx configuration after this update to make sure that the headers are passed properly to the remotely server?

**Comment by Jay-Rad** [comment] 2019-04-28 18:41
I added a small change that might help.  If not, there's also a note in their docs about dual-mode sockets, under the KnownProxies section.  See if that applies to you.  https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-2.2#forwarded-headers-middleware-options 

If it's still not working, then you'll need to have Nginx forward requests to Remotely on the same box.

Unfortunately, I don't have time to develop and test for environments that I'm not actively using.  I know it sucks to have a "works on my box" mentality, but I simply don't have the time.

**Closed by Jay-Rad** 2019-04-28 18:41 UTC
