### ISSUE TITLE
Organization Users Only List 1 User (Logged In User)

### ISSUE THREAD

**Issue by McChicken2020** [Jay-Rad/Remotely#70] opened 2020-01-15 22:03 UTC
https://github.com/Jay-Rad/Remotely/blob/74b69b38308b5e9903a40945728c0864d9714889/Server/Areas/Identity/Pages/Account/Manage/Organization.cshtml.cs#L40

This only returns one user, the person who is logged in, regardless of how many are in organization.

**Comment by Jay-Rad** [comment] 2020-01-16 07:01
This was caused by an auto-property initializer.  Fixed in commit 9a8b74956fcd5c13cefdc3348b0bf23b039a679c.

**Closed by Jay-Rad** 2020-01-16 07:01 UTC
